spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${APP_DB_URL}
    username: ${APP_DB_USERNAME}
    password: ${APP_DB_PASSWORD}

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration-seconds: 1800
  refresh-token-expiration-seconds: 604800